### Entorno local
#@baseUrl = http://localhost:7071/api

### Entorno desplegado (reemplazar con valores del resumen de deploy.ps1)
@baseUrl =  [BASE-URL]
###

# GET - HolaMundo
GET {{baseUrl}}/HolaMundo

###

# POST - OrdersReporter
POST {{baseUrl}}/OrdersReporter
Content-Type: application/json

{
    "CustomerName": "Litware, Inc.",
    "StartDate": "2026-01-01",
    "EndDate": "2026-01-31",
    "Orders": [
        {
            "OrderNumber": "ORD-CID-069-001",
            "OrderDate": "2026-01-04",
            "OrderLineNumber": 1,
            "ProductName": "Sport-100 Helmet, Black",
            "BrandName": "Contoso Outdoor",
            "CategoryName": "Helmets",
            "Quantity": 6.0,
            "UnitPrice": 34.99,
            "LineTotal": 209.94
        },
        {
            "OrderNumber": "ORD-CID-069-001",
            "OrderDate": "2026-01-04",
            "OrderLineNumber": 2,
            "ProductName": "HL Road Frame - Red, 62",
            "BrandName": "Contoso Outdoor",
            "CategoryName": "Road Frames",
            "Quantity": 10.0,
            "UnitPrice": 1431.5,
            "LineTotal": 14315.0
        },
        {
            "OrderNumber": "ORD-CID-069-001",
            "OrderDate": "2026-01-04",
            "OrderLineNumber": 3,
            "ProductName": "Long-Sleeve Logo Jersey, S",
            "BrandName": "Contoso Outdoor",
            "CategoryName": "Jerseys",
            "Quantity": 8.0,
            "UnitPrice": 49.99,
            "LineTotal": 399.92
        },
        {
            "OrderNumber": "ORD-CID-069-003",
            "OrderDate": "2026-01-08",
            "OrderLineNumber": 1,
            "ProductName": "HL Road Frame - Black, 58",
            "BrandName": "Contoso Outdoor",
            "CategoryName": "Road Frames",
            "Quantity": 3.0,
            "UnitPrice": 1431.5,
            "LineTotal": 4294.5
        },
        {
            "OrderNumber": "ORD-CID-069-003",
            "OrderDate": "2026-01-08",
            "OrderLineNumber": 2,
            "ProductName": "HL Road Frame - Red, 44",
            "BrandName": "Contoso Outdoor",
            "CategoryName": "Road Frames",
            "Quantity": 7.0,
            "UnitPrice": 1431.5,
            "LineTotal": 10020.5
        },
        {
            "OrderNumber": "ORD-CID-069-002",
            "OrderDate": "2026-01-17",
            "OrderLineNumber": 1,
            "ProductName": "HL Road Frame - Red, 62",
            "BrandName": "Contoso Outdoor",
            "CategoryName": "Road Frames",
            "Quantity": 2.0,
            "UnitPrice": 1431.5,
            "LineTotal": 2863.0
        },
        {
            "OrderNumber": "ORD-CID-069-002",
            "OrderDate": "2026-01-17",
            "OrderLineNumber": 2,
            "ProductName": "LL Road Frame - Black, 60",
            "BrandName": "Contoso Outdoor",
            "CategoryName": "Road Frames",
            "Quantity": 4.0,
            "UnitPrice": 337.22,
            "LineTotal": 1348.88
        },
        {
            "OrderNumber": "ORD-CID-069-002",
            "OrderDate": "2026-01-17",
            "OrderLineNumber": 3,
            "ProductName": "HL Road Frame - Red, 56",
            "BrandName": "Contoso Outdoor",
            "CategoryName": "Road Frames",
            "Quantity": 6.0,
            "UnitPrice": 1431.5,
            "LineTotal": 8589.0
        },
        {
            "OrderNumber": "ORD-CID-069-002",
            "OrderDate": "2026-01-17",
            "OrderLineNumber": 4,
            "ProductName": "Long-Sleeve Logo Jersey, S",
            "BrandName": "Contoso Outdoor",
            "CategoryName": "Jerseys",
            "Quantity": 10.0,
            "UnitPrice": 49.99,
            "LineTotal": 499.9
        },
        {
            "OrderNumber": "ORD-CID-069-002",
            "OrderDate": "2026-01-17",
            "OrderLineNumber": 5,
            "ProductName": "AWC Logo Cap",
            "BrandName": "Contoso Outdoor",
            "CategoryName": "Caps",
            "Quantity": 3.0,
            "UnitPrice": 8.99,
            "LineTotal": 26.97
        },
        {
            "OrderNumber": "ORD-CID-069-004",
            "OrderDate": "2026-01-22",
            "OrderLineNumber": 1,
            "ProductName": "Long-Sleeve Logo Jersey, L",
            "BrandName": "Contoso Outdoor",
            "CategoryName": "Jerseys",
            "Quantity": 2.0,
            "UnitPrice": 49.99,
            "LineTotal": 99.98
        },
        {
            "OrderNumber": "ORD-CID-069-004",
            "OrderDate": "2026-01-22",
            "OrderLineNumber": 2,
            "ProductName": "Sport-100 Helmet, Blue",
            "BrandName": "Contoso Outdoor",
            "CategoryName": "Helmets",
            "Quantity": 5.0,
            "UnitPrice": 34.99,
            "LineTotal": 174.95
        },
        {
            "OrderNumber": "ORD-CID-069-004",
            "OrderDate": "2026-01-22",
            "OrderLineNumber": 3,
            "ProductName": "Sport-100 Helmet, Blue",
            "BrandName": "Contoso Outdoor",
            "CategoryName": "Helmets",
            "Quantity": 1.0,
            "UnitPrice": 34.99,
            "LineTotal": 34.99
        },
        {
            "OrderNumber": "ORD-CID-069-004",
            "OrderDate": "2026-01-22",
            "OrderLineNumber": 4,
            "ProductName": "HL Road Frame - Red, 62",
            "BrandName": "Contoso Outdoor",
            "CategoryName": "Road Frames",
            "Quantity": 8.0,
            "UnitPrice": 1431.5,
            "LineTotal": 11452.0
        },
        {
            "OrderNumber": "ORD-CID-069-004",
            "OrderDate": "2026-01-22",
            "OrderLineNumber": 5,
            "ProductName": "HL Road Frame - Red, 44",
            "BrandName": "Contoso Outdoor",
            "CategoryName": "Road Frames",
            "Quantity": 2.0,
            "UnitPrice": 1431.5,
            "LineTotal": 2863.0
        },
        {
            "OrderNumber": "ORD-CID-069-005",
            "OrderDate": "2026-01-25",
            "OrderLineNumber": 1,
            "ProductName": "HL Road Frame - Black, 58",
            "BrandName": "Contoso Outdoor",
            "CategoryName": "Road Frames",
            "Quantity": 7.0,
            "UnitPrice": 1431.5,
            "LineTotal": 10020.5
        },
        {
            "OrderNumber": "ORD-CID-069-005",
            "OrderDate": "2026-01-25",
            "OrderLineNumber": 2,
            "ProductName": "HL Road Frame - Black, 58",
            "BrandName": "Contoso Outdoor",
            "CategoryName": "Road Frames",
            "Quantity": 6.0,
            "UnitPrice": 1431.5,
            "LineTotal": 8589.0
        },
        {
            "OrderNumber": "ORD-CID-069-005",
            "OrderDate": "2026-01-25",
            "OrderLineNumber": 3,
            "ProductName": "HL Road Frame - Red, 48",
            "BrandName": "Contoso Outdoor",
            "CategoryName": "Road Frames",
            "Quantity": 9.0,
            "UnitPrice": 1431.5,
            "LineTotal": 12883.5
        },
        {
            "OrderNumber": "ORD-CID-069-005",
            "OrderDate": "2026-01-25",
            "OrderLineNumber": 4,
            "ProductName": "LL Road Frame - Black, 62",
            "BrandName": "Contoso Outdoor",
            "CategoryName": "Road Frames",
            "Quantity": 10.0,
            "UnitPrice": 337.22,
            "LineTotal": 3372.2
        },
        {
            "OrderNumber": "ORD-CID-069-005",
            "OrderDate": "2026-01-25",
            "OrderLineNumber": 5,
            "ProductName": "LL Road Frame - Black, 60",
            "BrandName": "Contoso Outdoor",
            "CategoryName": "Road Frames",
            "Quantity": 7.0,
            "UnitPrice": 337.22,
            "LineTotal": 2360.54
        }
    ]
}