---
config:
  look: neo
---
flowchart LR

  subgraph CS["Copilot Studio"]
    Sofia["Sofía"]
    Orion["Orion (Orch.)"]
  end

  subgraph MF["Microsoft Fabric"]
    Aurelio["Aurelio (Op. Facts)"]
    Nora["Nora (Analytics)"]
  end

  subgraph AF["Azure AI Foundry"]
    Bruno["Bruno (Interpreter)"]
    Clara["Clara (Planner)"]
  end
  MF ~~~ AF
  Sofia L_Sofia_Orion_0@--> Orion
  Orion OP1@<-->|OP1| Aurelio
  Orion OP2@<-->|OP2| Bruno
  Orion AN1@<-->|AN1| Nora
  Orion AN2@<-->|AN2| Clara
  Orion L_Orion_Sofia_0@--> Sofia
  L_Sofia_Orion_0@{ curve: natural }
  L_Orion_Sofia_0@{ curve: natural }
  linkStyle 2 stroke:#E02828,stroke-width:3px,color:#E02828     %% OP1 - red
  linkStyle 3 stroke:#E02828,stroke-width:3px,color:#E02828     %% OP2 - red
  linkStyle 4 stroke:#2880E0,stroke-width:3px,color:#2880E0     %% AN1 - blue
  linkStyle 5 stroke:#2880E0,stroke-width:3px,color:#2880E0     %% AN2 - blue
