---
config:
  look: neo
---
flowchart LR

  subgraph CS["Copilot Studio"]
    Charles["Charles"]
    Bill((("Bill (Orch)")))
    Ric{{"Ric (Child)"}}
  end

  subgraph MF["Microsoft Fabric"]
    Jeffrey["Jeffrey (Op. Facts)"]
    Amy["Amy (Analytics)"]
  end

  subgraph AF["Azure AI Foundry"]
    Anders["Anders (Interpreter)"]
    Julie["Julie (Planner)"]
  end

  MF ~~~ AF
  Charles -- " " --> Bill
  Bill <-->|OP1| Jeffrey
  Bill <-->|OP2| Anders
  Bill <-->|AN1| Amy
  Bill <-->|AN2| Julie
  Bill -- " " --> Charles
  Bill --> Ric

  linkStyle 1 stroke:#E02828,stroke-width:3px,color:#E02828
  linkStyle 2 stroke:#E02828,stroke-width:3px,color:#E02828
  linkStyle 3 stroke:#2880E0,stroke-width:3px,color:#2880E0
  linkStyle 4 stroke:#2880E0,stroke-width:3px,color:#2880E0
  linkStyle 6 stroke:#32CD32,stroke-width:3px,color:#32CD32
