---
config:
  look: neo
---
flowchart LR

  subgraph CS["Copilot Studio"]
    Charles["Charles"]
    Bill((("Bill (Orch)")))
    Ric{{"Ric (Child)"}}
  end

  subgraph MF["Microsoft Fabric"]
    Mark["Mark (Op. Facts)"]
  end

  subgraph AF["Azure AI Foundry"]
    Anders["Anders (Executor)"]
    Julie["Julie (Planner)"]
  end

  %% Conexión invisible (Índice 0)
  MF ~~~ AF

  %% Conexiones
  Charles --> Bill
  Bill --> Charles
  Bill --> Ric
  Bill <-->|OP1| Mark
  Bill <-->|OP2| Anders
  Bill <-->|AN2| Julie

  %% Estilos Verdes: Internos CS (Charles y Ric)
  linkStyle 1,2,3 stroke:#32CD32,stroke-width:3px,color:#32CD32
  
  %% Estilos Rojos: Operativos (Mark y Anders)
  linkStyle 4,5 stroke:#E02828,stroke-width:3px,color:#E02828
  
  %% Estilos Azules: Analíticos (Julie)
  linkStyle 6 stroke:#2880E0,stroke-width:3px,color:#2880E0
